<?xml version="1.0"?>

<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define wheel radius, suspension parameters, and car dimensions -->
  <!-- kingpin_width = chassis_width + suspension_joint_with_chassis_offset_y * 2 -->
  <!-- wheel_separation = chassis_width + suspension_joint_with_chassis_offset_y * 2 + (steering_radius - wheel_width / 2) * 2 -->

  <xacro:property name="wheel_offset_x" value="0.226"/>
  <xacro:property name="wheel_offset_y" value="0.1485"/>
  <xacro:property name="wheel_offset_z" value="-0.2"/>

  <xacro:property name="wheel_radius" value="0.2"/>
  <xacro:property name="wheel_width" value="0.1"/>

  <xacro:property name="suspension_length" value="0.2"/>
  <xacro:property name="suspension_radius" value="0.1"/>

  <xacro:property name="chassis_height" value="0.5"/>
  <xacro:property name="chassis_width" value="0.8"/>
  <xacro:property name="chassis_length" value="1.6"/>
  <xacro:property name="wheelbase" value="1.5"/>
  
  <xacro:property name="steering_radius" value="0.2"/>
  
  <xacro:property name="suspension_joint_with_chassis_offset_z" value="0.0"/>
  <xacro:property name="suspension_joint_with_chassis_offset_y" value="0.0"/>
  <xacro:property name="suspension_joint_with_chassis_offset_x" value="0.0"/>

  <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />

  <material name="white">
      <color rgba="1 1 1 1" />
  </material>

  <material name="orange">
      <color rgba="1 0.3 0.1 1"/>
  </material>

  <material name="blue">
      <color rgba="0.2 0.2 1 1"/>
  </material>

  <material name="black">
      <color rgba="0 0 0 1"/>
  </material>

  <material name="red">
      <color rgba="1 0 0 1"/>
  </material>

  <link name="base_link">
  </link>

  <link name="base_footprint">
  </link>

  <joint name="base_footprint_joint" type="fixed">
      <parent link="base_link"/>
      <child link="base_footprint"/>
      <origin xyz="0 0 -0.138" rpy="0 0 0"/>
  </joint>

  <joint name="chassis_joint" type="fixed">
      <parent link="base_link"/>
      <child link="chassis_link"/>
      <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
  </joint>
    

  <!-- Car body -->
  <link name="chassis_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="chassis">
        <material>Gazebo/Blue</material>
  </gazebo>
  

  <!-- Front left wheel -->
  <joint name="front_left_steering_joint" type="revolute">
    <origin xyz="${wheelbase / 2 + suspension_joint_with_chassis_offset_x} ${chassis_width / 2 + suspension_joint_with_chassis_offset_y} -${suspension_joint_with_chassis_offset_z}"/>
    <parent link="chassis_link"/>
    <child link="front_left_suspension_link"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="1.0"/>
  </joint>

  <!-- Front right wheel -->
  <joint name="front_right_steering_joint" type="revolute">
    <origin xyz="${wheelbase / 2 + suspension_joint_with_chassis_offset_x} -${chassis_width / 2 + suspension_joint_with_chassis_offset_y} -${suspension_joint_with_chassis_offset_z}"/>
    <parent link="chassis_link"/>
    <child link="front_right_suspension_link"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="1.0"/>
  </joint>


  <!-- Rear left wheel -->
  <joint name="rear_left_chassis_joint" type="fixed">
    <origin xyz="-${wheelbase / 2 - suspension_joint_with_chassis_offset_x} ${chassis_width / 2 + suspension_joint_with_chassis_offset_y} -${suspension_joint_with_chassis_offset_z}"/>
    <parent link="chassis_link"/>
    <child link="rear_left_suspension_link"/>
  </joint>

  <!-- Rear ight wheel -->
  <joint name="rear_right_chassis_joint" type="fixed">
    <origin xyz="-${wheelbase / 2 - suspension_joint_with_chassis_offset_x} -${chassis_width / 2 + suspension_joint_with_chassis_offset_y} -${suspension_joint_with_chassis_offset_z}"/>
    <parent link="chassis_link"/>
    <child link="rear_right_suspension_link"/>
  </joint>


  <xacro:macro name="wheel" params="prefix">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
    </link>
    <gazebo reference="${prefix}_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
  </xacro:macro>

  <xacro:wheel prefix="front_left"/>
  <xacro:wheel prefix="front_right"/>
  <xacro:wheel prefix="rear_left"/>
  <xacro:wheel prefix="rear_right"/>


  <xacro:macro name="suspension" params="prefix">
    <link name="${prefix}_suspension_link">
      <visual>
        <geometry>
          <cylinder length="${suspension_length}" radius="${suspension_radius}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${suspension_length}" radius="${suspension_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.5"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
    </link>
    <gazebo reference="${prefix}_suspension">
        <material>Gazebo/Blue</material>
    </gazebo>
  </xacro:macro>

  <xacro:suspension prefix="front_left"/>
  <xacro:suspension prefix="front_right"/>
  <xacro:suspension prefix="rear_left"/>
  <xacro:suspension prefix="rear_right"/>


  <xacro:macro name="hub" params="prefix">
    <link name="${prefix}_hub_link">
      <visual>
        <geometry>
          <sphere radius="0.01"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.01"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
    </link>
    <gazebo reference="${prefix}_hub">
        <material>Gazebo/Blue</material>
    </gazebo>
  </xacro:macro>

  <xacro:hub prefix="front_left"/>
  <xacro:hub prefix="front_right"/>
  <xacro:hub prefix="rear_left"/>
  <xacro:hub prefix="rear_right"/>


  <xacro:macro name="suspension_with_hub_joint" params="prefix origin_xyz">
    <joint name="${prefix}_suspension_with_hub_joint" type="prismatic">
      <origin xyz="${origin_xyz}"/>
      <parent link="${prefix}_suspension_link"/>
      <child link="${prefix}_hub_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="100" velocity="1.0" lower="-${suspension_length}" upper="0.0"/>
      <dynamics damping="0.7"/>
    </joint>
  </xacro:macro>

  <xacro:suspension_with_hub_joint prefix="front_left" origin_xyz="0 ${steering_radius} 0"/>
  <xacro:suspension_with_hub_joint prefix="front_right" origin_xyz="0 -${steering_radius} 0"/>
  <xacro:suspension_with_hub_joint prefix="rear_left" origin_xyz="0 ${steering_radius} 0"/>
  <xacro:suspension_with_hub_joint prefix="rear_right" origin_xyz="0 -${steering_radius} 0"/>


  <xacro:macro name="hub_with_wheel_joint" params="prefix">
    <joint name="${prefix}_hub_with_wheel_joint" type="continuous">
      <origin xyz="0 0 0"/>
      <parent link="${prefix}_hub_link"/>
      <child link="${prefix}_wheel_link"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:hub_with_wheel_joint prefix="front_left"/>
  <xacro:hub_with_wheel_joint prefix="front_right"/>
  <xacro:hub_with_wheel_joint prefix="rear_left"/>
  <xacro:hub_with_wheel_joint prefix="rear_right"/>


</robot>

