<?xml version="1.0"?>

<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="wheel_offset_x" value="0.226"/>
  <xacro:property name="wheel_offset_y" value="0.1485"/>
  <xacro:property name="wheel_offset_z" value="-1.0"/>

  <xacro:property name="wheel_radius" value="0.2"/>
  <xacro:property name="wheel_width" value="0.1"/>

  <xacro:property name="body_height" value="0.2"/>
  <xacro:property name="body_width" value="0.8"/>
  <xacro:property name="body_length" value="1.6"/>

  <xacro:property name="wheeltrack" value="1.5"/>
  <xacro:property name="wheelbase" value="1.5"/>
  
  <xacro:property name="chassis_offset_z" value="0.2"/>
  <xacro:property name="chassis_offset_y" value="0.0"/>
  <xacro:property name="chassis_offset_x" value="0.0"/>

  <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />

  <link name="base_link">
  </link>

  <link name="base_footprint">
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin rpy="0 0 0" xyz="0 0 -0.138"/>
  </joint>

  <joint name="body_joint" type="fixed">
    <parent link="base_link"/>
    <child link="body_link"/>
    <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
  </joint>
    
  <link name="body_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="body">
    <material>Gazebo/Blue</material>
  </gazebo>


  <xacro:macro name="wheel" params="prefix">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
    </link>
    <gazebo reference="${prefix}_wheel_link">
        <material>Gazebo/Blue</material>
    </gazebo>
  </xacro:macro>

  <xacro:wheel prefix="front_left"/>
  <xacro:wheel prefix="front_right"/>
  <xacro:wheel prefix="rear_left"/>
  <xacro:wheel prefix="rear_right"/>


  <xacro:macro name="wheel_joint" params="prefix origin_xyz">
    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="${origin_xyz}"/>
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel_joint prefix="front_left" origin_xyz="${wheelbase / 2 + chassis_offset_x} ${wheeltrack / 2 + chassis_offset_y} ${chassis_offset_z}"/>
  <xacro:wheel_joint prefix="front_right" origin_xyz="${wheelbase / 2 + chassis_offset_x} ${-wheeltrack / 2 + chassis_offset_y} ${chassis_offset_z}"/>
  <xacro:wheel_joint prefix="rear_left" origin_xyz="${-wheelbase / 2 + chassis_offset_x} ${wheeltrack / 2 + chassis_offset_y} ${chassis_offset_z}"/>
  <xacro:wheel_joint prefix="rear_right" origin_xyz="${-wheelbase / 2 + chassis_offset_x} ${-wheeltrack / 2 + chassis_offset_y} ${chassis_offset_z}"/>


</robot>

