<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <gazebo>
        <!--plugin
            filename="gz-sim-pose-publisher-system"
            name="gz::sim::systems::PosePublisher">
            <publish_link_pose>true</publish_link_pose>
            <use_pose_vector_msg>true</use_pose_vector_msg>
            <static_publisher>true</static_publisher>
            <static_update_frequency>1</static_update_frequency>
        </plugin-->

        <!--plugin
            filename="gz-sim-odometry-publisher-system"
            name="gz::sim::systems::OdometryPublisher">
            <odom_frame>robot/odom</odom_frame>
            <robot_base_frame>robot/base_link</robot_base_frame>
            <odom_publish_frequency>50</odom_publish_frequency>
        </plugin-->

        <!-- <plugin
            filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
        </plugin> -->

        <plugin 
            filename="libgz-sim7-ackermann-steering-system.so"
            name="gz::sim::v7::systems::AckermannSteering">

            <steering_only>false</steering_only>
            <!-- <use_actuator_msg></use_actuator_msg>
            <actuator_number></actuator_number> -->
            <!-- <steer_p_gain></steer_p_gain> -->

            <left_steering_joint>front_left_steering_joint</left_steering_joint>
            <right_steering_joint>front_right_steering_joint</right_steering_joint>

            <left_joint>front_left_hub_with_wheel_joint</left_joint>
            <right_joint>front_right_hub_with_wheel_joint</right_joint>

            <left_joint>rear_left_hub_with_wheel_joint</left_joint>
            <right_joint>rear_right_hub_with_wheel_joint</right_joint>

            <wheel_separation>${chassis_width + suspension_joint_with_chassis_offset_y * 2 + (steering_radius - wheel_width / 2) * 2}</wheel_separation>
            <kingpin_width>${chassis_width + suspension_joint_with_chassis_offset_y * 2}</kingpin_width>
            <wheel_base>${chassis_width + suspension_joint_with_chassis_offset_y * 2 + steering_radius * 2}</wheel_base>
            <steering_limit>0.5</steering_limit>
            <wheel_radius>${wheel_radius}</wheel_radius>

        </plugin>
    </gazebo>
    
</robot>
