<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Define wheel radius, suspension parameters, and car dimensions -->
  <xacro:property name="wheel_radius" value="0.2"/>
  <xacro:property name="suspension_length" value="0.2"/>
  <xacro:property name="track_width" value="0.7"/>
  <xacro:property name="wheelbase" value="1.5"/>
  <xacro:property name="steering_radius" value="0.1"/>
  <xacro:property name="suspension_joint_with_chassis_offset_z" value="0.1"/>
  <xacro:property name="suspension_joint_with_chassis_offset_y" value="0.1"/>
  <xacro:property name="suspension_joint_with_chassis_offset_x" value="0.1"/>


  <!-- Car body -->
  <link name="chassis">
    <visual>
      <geometry>
        <box size="${wheelbase} ${track_width} 0.5"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${wheelbase} ${track_width} 0.5"/>
      </geometry>
    </collision>
  </link>

  <!-- Front left wheel -->
  <joint name="front_left_steering_joint" type="revolute">
    <origin xyz="${wheelbase / 2 + suspension_joint_with_chassis_offset_x} ${track_width / 2 + suspension_joint_with_chassis_offset_y} -${suspension_joint_with_chassis_offset_z}"/>
    <parent link="chassis"/>
    <child link="front_left_suspension"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="1.0"/>
  </joint>

  <!-- Front right wheel -->
  <joint name="front_right_steering_joint" type="revolute">
    <origin xyz="${wheelbase / 2 + suspension_joint_with_chassis_offset_x} -${track_width / 2 + suspension_joint_with_chassis_offset_y} -${suspension_joint_with_chassis_offset_z}"/>
    <parent link="chassis"/>
    <child link="front_right_suspension"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="1.0"/>
  </joint>

  <!-- Rear left wheel -->
  <joint name="rear_left_chassis_joint" type="fixed">
    <origin xyz="-${wheelbase / 2 - suspension_joint_with_chassis_offset_x} ${track_width / 2 + suspension_joint_with_chassis_offset_y} -${suspension_joint_with_chassis_offset_z}"/>
    <parent link="chassis"/>
    <child link="rear_left_suspension"/>
  </joint>

  <!-- Rear ight wheel -->
  <joint name="rear_right_chassis_joint" type="fixed">
    <origin xyz="-${wheelbase / 2 - suspension_joint_with_chassis_offset_x} -${track_width / 2 + suspension_joint_with_chassis_offset_y} -${suspension_joint_with_chassis_offset_z}"/>
    <parent link="chassis"/>
    <child link="rear_right_suspension"/>
  </joint>

  <!-- Front left wheel -->
  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Front right wheel -->
  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Rear left wheel -->
  <link name="rear_left_wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Rear right wheel -->
  <link name="rear_right_wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <origin rpy="1.571 0 0" xyz="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>


  <!-- Front left suspension -->
  <link name="front_left_suspension">
    <visual>
      <geometry>
        <cylinder length="${suspension_length}" radius="0.05"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${suspension_length}" radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Front right suspension -->
  <link name="front_right_suspension">
    <visual>
      <geometry>
        <cylinder length="${suspension_length}" radius="0.05"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${suspension_length}" radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Rear left suspension -->
  <link name="rear_left_suspension">
    <visual>
      <geometry>
        <cylinder length="${suspension_length}" radius="0.05"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${suspension_length}" radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Rear right suspension -->
  <link name="rear_right_suspension">
    <visual>
      <geometry>
        <cylinder length="${suspension_length}" radius="0.05"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${suspension_length}" radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Connect front left wheel to suspension -->
  <joint name="front_left_suspension_joint" type="prismatic">
    <origin xyz="0 ${steering_radius} 0"/>
    <parent link="front_left_suspension"/>
    <child link="front_left_wheel"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${suspension_length}" upper="0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Connect front right wheel to suspension -->
  <joint name="front_right_suspension_joint" type="prismatic">
    <origin xyz="0 -${steering_radius} 0"/>
    <parent link="front_right_suspension"/>
    <child link="front_right_wheel"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${suspension_length}" upper="0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Connect rear left wheel to suspension -->
  <joint name="rear_left_suspension_joint" type="prismatic">
    <origin xyz="0 ${steering_radius} 0"/>
    <parent link="rear_left_suspension"/>
    <child link="rear_left_wheel"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${suspension_length}" upper="0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Connect rear right wheel to suspension -->
  <joint name="rear_right_suspension_joint" type="prismatic">
    <origin xyz="0 -${steering_radius} 0"/>
    <parent link="rear_right_suspension"/>
    <child link="rear_right_wheel"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${suspension_length}" upper="0"/>
    <dynamics damping="0.7"/>
  </joint>
</robot>

